[install]
description = "setup .venv and install dependencies"
commands = "uv sync --all-extras --dev"

[format]
description = "format code"
commands = ["uv run ruff check", "uv run ruff format"]

[lint]
description = "run mypy"
commands = "uv run mypy ."

[test]
description = "run tests"
dependencies = "uv pip install pytest"
commands = "uv run pytest -v ."
cleanup = "rm -rf .venv/ .pytest_cache/"

[teardown]
description = "remove venv and cache"
commands = "rm -rf .venv/ .ruff_cache/ .pdm-build/ .pytest_cache/"

[run]
description = "jobs pipeline"
suite = ["install", "format", "lint", "teardown"]
