[params]
flag = "dev"
fmt = "format"

[install]
description = "setup .venv and install dependencies"
commands = "uv sync --all-extras --@@flag"

[format]
description = "format code"
commands = ["uv run ruff check", "uv run ruff @@fmt"]

[lint]
description = "run mypy"
commands = "uv run mypy ."

[teardown]
description = "remove venv and cache"
commands = "rm -rf .venv/ .ruff_cache/ .mypy_cache/"

[run]
description = "tasks pipeline"
main = ["install", "format", "lint"]
