[install]
description = "setup .venv and install dependencies"
commands = "uv sync --all-extras --dev"

[format]
description = "format code"
commands = ["uv run ruff check", "uv run ruff format"]

[test]
description = "run tests"
commands = "uv run pytest -v --cov=./pyrio --cov-fail-under=90 --cov-report=xml"

[deps_test]
description = "run tests"
dependencies = "uv sync --all-extras --dev"
commands = "uv run pytest -v --cov=./pyrio --cov-fail-under=90 --cov-report=xml"

[cleanup]
description = "remove venv and cache"
commands = "rm -rf .venv/ .ruff_cache/ .pdm-build/ .pytest_cache/"

[run]
description = "jobs pipeline"
suite = ["install", "format"]
